In [14]:
# importing libraries pandas, matplotlib and seaborn to load dataframe and visualization of data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
# Importing “train_test_split” from “sklearn.model_selection”. 
from sklearn.model_selection import train_test_split

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
# Importing tree, Pipeline, GridSearchCV from sklearn
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [18]:
from sklearn.metrics import make_scorer,f1_score, confusion_matrix
import matplotlib.pyplot as plt

In [19]:
%matplotlib inline

In [7]:
# from google.colab import drive

In [8]:
# drive.mount('/content/drive')

Mounted at /content/drive


In [51]:
%%time
# This is a countrywide car accident dataset, which covers 49 states of the USA. 
# The accident data are collected from February 2016 to June 2020, 
US_Accidents_Feb16_to_June20_data =pd.read_csv('../FinalProject/data/US_Accidents_June20.csv',encoding="utf-8" )
US_Accidents_Feb16_to_June20_data.shape

Wall time: 27.1 s


(3513617, 49)

In [52]:
US_Accidents_Feb16_to_June20_data.columns

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [53]:
US_Accidents_Feb16_to_June20_data['State'].unique()

array(['OH', 'WV', 'CA', 'FL', 'GA', 'SC', 'NE', 'IA', 'IL', 'MO', 'WI',
       'IN', 'MI', 'NJ', 'NY', 'CT', 'MA', 'RI', 'NH', 'PA', 'KY', 'MD',
       'VA', 'DC', 'DE', 'TX', 'WA', 'OR', 'AL', 'TN', 'NC', 'KS', 'LA',
       'OK', 'CO', 'UT', 'AZ', 'MN', 'MS', 'NV', 'ME', 'AR', 'ID', 'VT',
       'NM', 'ND', 'WY', 'SD', 'MT'], dtype=object)

###### County level demographics - Population distribution among different age groups at county level. 

In [ ]:
# State - Florida
US_demographic_data_Florida =pd.read_csv('../FinalProject/data/cc-est2019-alldata-12_Florida.csv')
US_demographic_data_Florida.shape

(15276, 80)

In [21]:
# State - California
US_demographic_data_California =pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/cc-est2019-alldata-06_California.csv')
US_demographic_data_California.shape

(13224, 80)

In [24]:
# State - Texas
US_demographic_data_Texas =pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/cc-est2019-alldata-48_texas.csv')
US_demographic_data_Texas.shape

(57912, 80)

In [10]:
# State - Virginia
US_demographic_data_Virginia =pd.read_csv('../FinalProject/data/cc-est2019-alldata-51_Virginia.csv')
US_demographic_data_Virginia.shape

(30324, 80)

In [ ]:
# State - SouthCarolina
US_demographic_data_SouthCarolina =pd.read_csv('../FinalProject/data/cc-est2019-alldata-45_SouthCarolina.csv')
US_demographic_data_SouthCarolina.shape

(10488, 80)

In [ ]:
# State - Pennsylvania
US_demographic_data_Pennsylvania =pd.read_csv('../FinalProject/data/cc-est2019-alldata-42_Pennsylvania.csv')
US_demographic_data_Pennsylvania.shape

(15276, 80)

In [ ]:
# State - NewYork
US_demographic_data_NewYork =pd.read_csv('../FinalProject/data/cc-est2019-alldata-36_NewYork.csv')
US_demographic_data_NewYork.shape

(14136, 80)

In [ ]:
# State - NorthCarolina
US_demographic_data_NorthCarolina =pd.read_csv('../FinalProject/data/cc-est2019-alldata-37_NorthCarolina.csv')
US_demographic_data_NorthCarolina.shape

(22800, 80)

In [11]:
# demographic_states_dataframe = [US_demographic_data_Florida,US_demographic_data_California,US_demographic_data_Texas,US_demographic_data_Virginia,US_demographic_data_SouthCarolina,US_demographic_data_Pennsylvania,US_demographic_data_NewYork,US_demographic_data_NorthCarolina]
# demographic_states_dataframe = [US_demographic_data_California,US_demographic_data_Texas]
demographic_states_dataframe = [US_demographic_data_Virginia]

In [12]:
# function concat demographic dataframes for different states
def concat_dataframe_by_row(dataframes):
    merged_df = pd.concat(demographic_states_dataframe, axis=0)
    return merged_df

In [13]:
US_demographic_data = concat_dataframe_by_row(demographic_states_dataframe)
US_demographic_data.shape

(30324, 80)

######  US Accidents Feb16 to June20_data-  by states. 


In [14]:
# Function to filter dataframe by state
def filter_dataframe_by_state(df,state):
    updated_df = df[df['State']==state]
    return updated_df

In [15]:
# US accidents data for only florida
# 
# US_Accidents_data_by_state = filter_dataframe_by_state(US_Accidents_Feb16_to_June20_data,'FL')
# US_Accidents_data_by_state.shape

######   Concat US Accidents Feb16 to June20_data-  by states. 

In [20]:
US_Accidents_Feb16_to_June20_data.State.unique()

array(['OH', 'WV', 'CA', 'FL', 'GA', 'SC', 'NE', 'IA', 'IL', 'MO', 'WI',
       'IN', 'MI', 'NJ', 'NY', 'CT', 'MA', 'RI', 'NH', 'PA', 'KY', 'MD',
       'VA', 'DC', 'DE', 'TX', 'WA', 'OR', 'AL', 'TN', 'NC', 'KS', 'LA',
       'OK', 'CO', 'UT', 'AZ', 'MN', 'MS', 'NV', 'ME', 'AR', 'ID', 'VT',
       'NM', 'ND', 'WY', 'SD', 'MT'], dtype=object)

In [17]:
#States_records = ['FL','CA', 'TX', 'VA', 'SC', 'PA', 'NY', 'NC']
#States_records = ['CA', 'TX']
States_records =['VA']

In [18]:
# function filter US accidents by States
def concat_dataframe_by_states_US_Accidents(dataframe,States_records):
    data = []
    for state in States_records:
        data.append(filter_dataframe_by_state(dataframe,state))

    merged_t = pd.concat(data, axis=0)
    return merged_t
    

In [19]:
US_Accidents_Feb16_to_June20_data_by_states =concat_dataframe_by_states_US_Accidents(US_Accidents_Feb16_to_June20_data,States_records)
US_Accidents_Feb16_to_June20_data_by_states.shape

(96075, 49)

####  Feature Reduction for US_Accidents_Feb16_to_June20_data_by_states

In [8]:
# For US_Accidents_Feb16_to_June20_data_by_states dataset
US_Accidents_Feb16_to_June20_data.shape

(3513617, 49)

In [22]:
# del(US_Accidents_Feb16_to_June20_data)
# del(US_demographic_data)

In [21]:
# Retrieving records that has 70% of total records as null values
US_Accidents_Feb16_to_June20_data.isnull().sum().sort_values().tail(20)

Civil_Twilight               115
Astronomical_Twilight        115
Nautical_Twilight            115
Zipcode                     1069
Timezone                    3880
Airport_Code                6758
Weather_Timestamp          43323
Pressure(in)               55882
Wind_Direction             58874
Temperature(F)             65732
Humidity(%)                69687
Visibility(mi)             75856
Weather_Condition          76138
Wind_Speed(mph)           454609
TMC                      1034799
Wind_Chill(F)            1868249
Precipitation(in)        2025874
Number                   2262864
End_Lng                  2478818
End_Lat                  2478818
dtype: int64

In [ ]:
US_Accidents_Feb16_to_June20_data

In [22]:
# Dropping features because 70% of data is null
US_Accidents_Feb16_to_June20_data.drop(['Precipitation(in)','Number', 'End_Lng', 'End_Lat','Wind_Chill(F)','Wind_Speed(mph)','TMC'], axis=1, inplace=True)
US_Accidents_Feb16_to_June20_data.shape


(3513617, 42)

In [23]:
# Dropping features which doesn't add much value for model creation
US_Accidents_Feb16_to_June20_data.drop(['Country','Zipcode','ID','Source','Description','Street','Weather_Timestamp','Turning_Loop','City'], axis=1, inplace=True)
US_Accidents_Feb16_to_June20_data.shape
# Traffic_Signal, Turning_Loop


(3513617, 33)

In [24]:
US_Accidents_Feb16_to_June20_data['Start_Time'] = pd.to_datetime(US_Accidents_Feb16_to_June20_data['Start_Time'])
US_Accidents_Feb16_to_June20_data['Start_Time_Year'] = US_Accidents_Feb16_to_June20_data['Start_Time'].dt.year
US_Accidents_Feb16_to_June20_data['Start_Time_Year'].unique()

array([2016, 2017, 2020, 2019, 2018], dtype=int64)

In [29]:
US_Accidents_Feb16_to_June20_data['Start_Time'].head(5),US_Accidents_Feb16_to_June20_data['End_Time'].head(5)

(0   2016-02-08 05:46:00
 1   2016-02-08 06:07:59
 2   2016-02-08 06:49:27
 3   2016-02-08 07:23:34
 4   2016-02-08 07:39:07
 Name: Start_Time, dtype: datetime64[ns],
 0   2016-02-08 11:00:00
 1   2016-02-08 06:37:59
 2   2016-02-08 07:19:27
 3   2016-02-08 07:53:34
 4   2016-02-08 08:09:07
 Name: End_Time, dtype: datetime64[ns])

In [28]:
US_Accidents_Feb16_to_June20_data[['End_Time']]= US_Accidents_Feb16_to_June20_data[['End_Time']].apply(pd.to_datetime)

In [32]:
duration = US_Accidents_Feb16_to_June20_data['End_Time']- US_Accidents_Feb16_to_June20_data['Start_Time']
US_Accidents_Feb16_to_June20_data['duration'] = duration.astype('timedelta64[s]')

In [38]:
# Dropping features 'Start_Time' and 'End_Time'
US_Accidents_Feb16_to_June20_data.drop(['Start_Time','End_Time'], axis=1, inplace=True)
US_Accidents_Feb16_to_June20_data.shape

(3513617, 33)

In [41]:
# Dropping features 'Start_Lat' and 'Start_Lng'
US_Accidents_Feb16_to_June20_data.drop(['Start_Lat','Start_Lng'], axis=1, inplace=True)


In [42]:

# Dropping features where 99% of data belongs to only one category there is no variance in data
# 'Turning_Loop', 'Traffic_Calming', 'Stop', 'Station', 'Roundabout', 'Railway','No_Exit','Give_Way','Crossing', 'Bump', 'Amenity'
US_Accidents_Feb16_to_June20_data.drop(['Traffic_Calming', 'Stop', 'Station', 'Roundabout', 'Railway','No_Exit','Give_Way','Crossing', 'Bump', 'Amenity'], axis=1, inplace=True)
US_Accidents_Feb16_to_June20_data.shape


(3513617, 21)

In [48]:
US_Accidents_Feb16_to_June20_data['Wind_Direction'].value_counts()

Calm        368282
CALM        217424
SSW         181645
South       177225
WNW         174115
SW          172252
WSW         165738
NW          164928
West        164624
SSE         163649
North       153252
NNW         147047
SE          132051
NNE         117475
NE          115931
ESE         114855
Variable    113897
ENE         112626
S           103970
East        103462
W            95115
N            70516
VAR          64523
E            60141
Name: Wind_Direction, dtype: int64

In [1]:
# Dropping features 'Timezone', 'Airport_Code'
# Dropping feature Wind_Direction - can be used for SVM later
US_Accidents_Feb16_to_June20_data.drop(['Wind_Direction'], axis=1, inplace=True)
US_Accidents_Feb16_to_June20_data.shape

In [ ]:
# 'Airport_Code'

### Feature transformation 

In [31]:
US_Accidents_Feb16_to_June20_data_by_states.columns

Index(['Severity', 'Distance(mi)', 'Side', 'County', 'State', 'Timezone',
       'Temperature(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)',
       'Weather_Condition', 'Junction', 'Traffic_Signal', 'Sunrise_Sunset',
       'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight',
       'Start_Time_Year'],
      dtype='object')

#### Converting categorical values with two outcomes into binary value 

In [32]:
day_night_mapping = {'Day':0,'Night':1}

In [33]:
# mapping categorical values Day = 0 and night= 1
# 'Sunrise_Sunset', 'Civil_Twilight','Nautical_Twilight', 'Astronomical_Twilight'
US_Accidents_Feb16_to_June20_data_by_states.Sunrise_Sunset.replace(dict(day_night_mapping), inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.Civil_Twilight.replace(dict(day_night_mapping), inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.Nautical_Twilight.replace(dict(day_night_mapping), inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.Astronomical_Twilight.replace(dict(day_night_mapping), inplace=True)


In [34]:
boolean_mapping = {True:1,False:0}
data_mapping = {'R':0,'L':1}

In [35]:
US_Accidents_Feb16_to_June20_data_by_states.Traffic_Signal.unique()

array([False,  True])

In [36]:
US_Accidents_Feb16_to_June20_data_by_states.Traffic_Signal.replace(dict(boolean_mapping),inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.Junction.replace(dict(boolean_mapping), inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.Side.replace(dict(data_mapping), inplace=True)

In [37]:
# Finding out columns with categorical values
US_Accidents_Feb16_to_June20_data_by_states.dtypes.unique() # unique data types 
US_Accidents_Feb16_to_June20_data_by_states.select_dtypes(exclude=['int','float']).columns #  Fetching columns with categorical values

Index(['Severity', 'Side', 'County', 'State', 'Timezone', 'Weather_Condition',
       'Junction', 'Traffic_Signal', 'Sunrise_Sunset', 'Civil_Twilight',
       'Nautical_Twilight', 'Astronomical_Twilight', 'Start_Time_Year'],
      dtype='object')

In [38]:
# Finding out columns with numerical values
US_Accidents_Feb16_to_June20_data_by_states.select_dtypes(include=['int','float']).columns

Index(['Distance(mi)', 'Temperature(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)'],
      dtype='object')

In [39]:
US_Accidents_Feb16_to_June20_data_by_states.shape

(96075, 18)

In [40]:
# Dropping null values from the dataframe
US_Accidents_Feb16_to_June20_data_by_states.dropna(inplace=True)
US_Accidents_Feb16_to_June20_data_by_states.shape

(90349, 18)

### Transformation and cleaning for demographic dataset

In [41]:
US_demographic_data.shape, US_demographic_data.columns

((30324, 80),
 Index(['SUMLEV', 'STATE', 'COUNTY', 'STNAME', 'CTYNAME', 'YEAR', 'AGEGRP',
        'TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE',
        'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE',
        'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE', 'WAC_MALE', 'WAC_FEMALE',
        'BAC_MALE', 'BAC_FEMALE', 'IAC_MALE', 'IAC_FEMALE', 'AAC_MALE',
        'AAC_FEMALE', 'NAC_MALE', 'NAC_FEMALE', 'NH_MALE', 'NH_FEMALE',
        'NHWA_MALE', 'NHWA_FEMALE', 'NHBA_MALE', 'NHBA_FEMALE', 'NHIA_MALE',
        'NHIA_FEMALE', 'NHAA_MALE', 'NHAA_FEMALE', 'NHNA_MALE', 'NHNA_FEMALE',
        'NHTOM_MALE', 'NHTOM_FEMALE', 'NHWAC_MALE', 'NHWAC_FEMALE',
        'NHBAC_MALE', 'NHBAC_FEMALE', 'NHIAC_MALE', 'NHIAC_FEMALE',
        'NHAAC_MALE', 'NHAAC_FEMALE', 'NHNAC_MALE', 'NHNAC_FEMALE', 'H_MALE',
        'H_FEMALE', 'HWA_MALE', 'HWA_FEMALE', 'HBA_MALE', 'HBA_FEMALE',
        'HIA_MALE', 'HIA_FEMALE', 'HAA_MALE', 'HAA_FEMALE', 'HNA_MALE',
        'HNA_FEMALE

In [42]:
# Index for columns  'WAC_MALE'  'HNAC_FEMALE'
US_demographic_data.columns.get_indexer(['WAC_MALE','HNAC_FEMALE'])


array([22, 79], dtype=int64)

In [43]:
# We are interested in analysis based on Origin  not on subcategory  of each cultural origin group
# Dropping columns from 'WAC_MALE' to 'HNAC_FEMALE'
columns_drop = US_demographic_data.columns[22:80].values.tolist()
US_demographic_data.drop(columns_drop,1,inplace=True)
US_demographic_data.shape

(30324, 22)

In [44]:
# Drop demographic records with YEAR column from 1 to 7 representing 2010 to 2015
US_demographic_data = US_demographic_data[~(US_demographic_data["YEAR"].isin(['1','2','3','4','5','6','7','8']))]
US_demographic_data.shape

(10108, 22)

In [45]:
# Replace YEAR column with values  9 to 12 representing year to scale 2016 to 2020
US_demographic_data.YEAR.replace(dict(zip(range(9, 13), range(2016, 2020))), inplace=True)
US_demographic_data.shape

D:\Softwares\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


(10108, 22)

In [46]:
# Summation of following features by age group
Variable_Summation = ['TOT_POP', 'TOT_MALE', 'TOT_FEMALE', 'WA_MALE', 'WA_FEMALE', 'BA_MALE',
'BA_FEMALE', 'IA_MALE', 'IA_FEMALE', 'AA_MALE', 'AA_FEMALE', 'NA_MALE',
'NA_FEMALE', 'TOM_MALE', 'TOM_FEMALE']

In [47]:
# Grouping by State, County, Year and Agegroup
US_demographic_data = US_demographic_data.groupby(['STNAME','CTYNAME','YEAR','AGEGRP'])[Variable_Summation].sum().reset_index()
US_demographic_data.shape

(10108, 19)

In [48]:
US_demographic_data = pd.pivot_table(US_demographic_data,index=['STNAME','CTYNAME','YEAR'], columns=['AGEGRP'], aggfunc=np.sum).reset_index()
US_demographic_data.shape

(532, 288)

In [49]:
US_demographic_data.columns = [level_0 + '_' + str(level_1) for level_0, level_1 in zip(US_demographic_data.columns.get_level_values(0), US_demographic_data.columns.get_level_values(1))]
US_demographic_data.shape

(532, 288)

In [50]:
US_demographic_data.head(1)

STNAME_         CTYNAME_  YEAR_  AA_FEMALE_0  AA_FEMALE_1  AA_FEMALE_2  \
0  Virginia  Accomack County   2016          139            6            5   

   AA_FEMALE_3  AA_FEMALE_4  AA_FEMALE_5  AA_FEMALE_6  ...  WA_MALE_9  \
0           13           10           13            4  ...        582   

   WA_MALE_10  WA_MALE_11  WA_MALE_12  WA_MALE_13  WA_MALE_14  WA_MALE_15  \
0         671         763         851         892         910         730   

   WA_MALE_16  WA_MALE_17  WA_MALE_18  
0         516         295         280  

[1 rows x 288 columns]

### Bring both the dataframes ( US_demographic_data and US_Accidents_Feb16_to_June20_data_by_states) on same scale for easy merging

#### US_Accidents 'Start_Time_Year' and US_demographic 'Year'

In [51]:

US_Accidents_Feb16_to_June20_data_by_states['Start_Time_Year'].unique(), US_demographic_data.YEAR_.unique()

(array([2016, 2017, 2020, 2019, 2018], dtype=int64),
 array([2016, 2017, 2018, 2019], dtype=int64))

#### US_Accidents 'states' and US_demographic 'STNAME_'

In [52]:
US_demographic_data.STNAME_.unique(), US_Accidents_Feb16_to_June20_data_by_states.State.unique()

(array(['Virginia'], dtype=object), array(['VA'], dtype=object))

In [53]:
state_mapping = {'Florida':'FL','California':'CA','Texas':'TX','Virginia':'VA','South Carolina':'SC','Pennsylvania':'PA','New York':'NY', 'North Carolina':'NC'}

In [54]:
US_demographic_data.STNAME_.replace(dict(state_mapping), inplace=True)
US_demographic_data.shape, US_demographic_data.STNAME_.unique(), US_Accidents_Feb16_to_June20_data_by_states.State.unique()

((532, 288), array(['VA'], dtype=object), array(['VA'], dtype=object))

#### US_Accidents 'County' and US_demographic 'CTYNAME'

In [55]:
US_demographic_data.CTYNAME_.value_counts().head(), US_Accidents_Feb16_to_June20_data_by_states.County.value_counts().head()

(Rockbridge County      4
 Sussex County          4
 Southampton County     4
 Radford city           4
 Fredericksburg city    4
 Name: CTYNAME_, dtype: int64,
 Fairfax County    14494
 Richmond City     14025
 Henrico            9749
 Loudoun            5786
 Chesterfield       4639
 Name: County, dtype: int64)

In [56]:
# Remove extra whitespace in both the datasets

In [57]:
# Replace whitespace with ""
US_demographic_data = US_demographic_data.assign(CTYNAME_= US_demographic_data['CTYNAME_'].str.replace(" ",""))

In [58]:
# Replace whitespace with ""
US_Accidents_Feb16_to_June20_data_by_states = US_Accidents_Feb16_to_June20_data_by_states.assign(County= US_Accidents_Feb16_to_June20_data_by_states['County'].str.replace(" ",""))

In [59]:
# Replace County with ""
US_demographic_data = US_demographic_data.assign(CTYNAME_= US_demographic_data['CTYNAME_'].str.replace("County",""))

In [60]:
US_demographic_data.dropna()
US_demographic_data.shape

(532, 288)

In [62]:
# # Creating backup files 
# US_demographic_data.to_csv('US_demographic_data_VA_optimized.csv',index=False)
# US_Accidents_Feb16_to_June20_data_by_states.to_csv('US_Accidents_Feb16_to_June20_data_by_states_VA_optimized.csv',index=False)


# Optimized datasets after feature extraction and cleaning

In [7]:
US_Accidents_Feb16_to_June20_data_by_states = pd.read_csv('US_Accidents_Feb16_to_June20_data_by_states.csv')
US_Accidents_Feb16_to_June20_data_by_states.shape

(1111202, 18)

In [8]:
US_demographic_data =pd.read_csv('US_demographic_data.csv')
US_demographic_data.shape

(1248, 288)

In [64]:
# del(US_Accidents_Feb16_to_June20_data_by_states)
# del(US_demographic_data)

### Merge the datasets US accidents and demographic data based on YEAR, STATE, COUNTY

In [63]:
%%time
US_Accidents_plus_Demographic_merged = US_Accidents_Feb16_to_June20_data_by_states.merge(US_demographic_data, how='left', left_on=["State","County","Start_Time_Year"], right_on=["STNAME_","CTYNAME_","YEAR_"])
US_Accidents_plus_Demographic_merged.shape

Wall time: 193 ms


(90349, 306)

In [10]:
# %%time
# # Creating backup files 
# US_Accidents_plus_Demographic_merged.to_csv('/content/drive/My Drive/Colab Notebooks/data/US_Accidents_plus_Demographic_merged.csv',index=False)

In [11]:
# US_Accidents_plus_Demographic_merged =pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/US_demographic_data.csv')
# US_Accidents_plus_Demographic_merged.shape

In [65]:
US_Accidents_plus_Demographic_merged.shape

(90349, 306)

## Decision Tree

In [66]:
# Droping duplicate features STNAME_, CTYNAME_, YEAR_
US_Accidents_plus_Demographic_merged.drop(['STNAME_', 'CTYNAME_', 'YEAR_'], axis=1, inplace=True)
US_Accidents_plus_Demographic_merged.shape

(90349, 303)

### Converting categorical values into numerical values using get_dummies 

In [67]:
# Categorical data types
US_Accidents_plus_Demographic_merged.select_dtypes(exclude=['int','float']).columns 

Index(['Severity', 'Side', 'County', 'State', 'Timezone', 'Weather_Condition',
       'Junction', 'Traffic_Signal', 'Sunrise_Sunset', 'Civil_Twilight',
       'Nautical_Twilight', 'Astronomical_Twilight', 'Start_Time_Year'],
      dtype='object')

In [72]:
US_Accidents_plus_Demographic_merged['Junction'].unique()

array([3, 2, 1, 4], dtype=int64)

In [69]:
margin = len(US_Accidents_plus_Demographic_merged)/ 100
margin

903.49

In [70]:
# Get the count of each value
value_counts = US_Accidents_plus_Demographic_merged.Weather_Condition.value_counts()

# Select the values where the count is less than 1% of the data
to_remove = value_counts[value_counts <= margin].index

# Keep rows where the Weather_Condition column is not in to_remove
US_Accidents_plus_Demographic_merged = US_Accidents_plus_Demographic_merged[~US_Accidents_plus_Demographic_merged.Weather_Condition.isin(to_remove)]

In [71]:
# Try to minimize the weather_condition features later on
Feature_list = ['State','Timezone','Weather_Condition']
US_Accidents_plus_Demographic_merged.shape

(85602, 303)

In [73]:
subset_dataframe_featurelist=[]
for variable in Feature_list:
    subset_dataframe_featurelist.append(pd.get_dummies(US_Accidents_plus_Demographic_merged[variable],prefix=variable, dummy_na=False))

In [74]:
merged_subset_dataframe_featurelist = pd.concat(subset_dataframe_featurelist, axis=1)
merged_subset_dataframe_featurelist.shape

(85602, 11)

In [75]:
%%time
US_Accidents_plus_Demographic_merged = pd.concat([merged_subset_dataframe_featurelist,US_Accidents_plus_Demographic_merged], axis=1)
US_Accidents_plus_Demographic_merged.shape

Wall time: 83 ms


(85602, 314)

In [76]:
# 'Side', 'State', 'Timezone','Weather_Condition', 
US_Accidents_plus_Demographic_merged.drop(['Side', 'State', 'Timezone','Weather_Condition'],axis=1, inplace=True)
US_Accidents_plus_Demographic_merged.shape

(85602, 310)

In [77]:
US_Accidents_plus_Demographic_merged.dropna(inplace = True)
US_Accidents_plus_Demographic_merged.shape

(36971, 310)

##### Severity as outcome binary values 0 or 1

In [78]:
US_Accidents_plus_Demographic_merged.Severity.unique()

array([3, 2, 1, 4], dtype=int64)

In [79]:
# Binary output
Severity_mapping = {1:0,2:0,3:1,4:1}
US_Accidents_plus_Demographic_merged.Severity.replace(dict(Severity_mapping), inplace=True)
US_Accidents_plus_Demographic_merged.shape

(36971, 310)

In [80]:
US_Accidents_plus_Demographic_merged.Severity.unique()

array([1, 0], dtype=int64)

In [25]:
# Split the training data into training and cross validation sets. 

In [112]:
# US_Accidents_plus_Demographic_merged.to_csv('US_Accidents_plus_Demographic_merged_without_na.csv',index=False)

In [81]:
y = pd.Series(US_Accidents_plus_Demographic_merged['Severity'])
y.shape

(36971,)

In [82]:
US_Accidents_plus_Demographic_merged.drop(['Severity'],axis=1, inplace=True)
US_Accidents_plus_Demographic_merged.shape

(36971, 309)

In [83]:
y_County = pd.Series(US_Accidents_plus_Demographic_merged.County)
y_County.shape

(36971,)

In [84]:
US_Accidents_plus_Demographic_merged.drop(['County'],axis=1, inplace=True)
US_Accidents_plus_Demographic_merged.shape

(36971, 308)

In [85]:
X= pd.DataFrame(US_Accidents_plus_Demographic_merged)
print(X.shape,y.shape)

(36971, 308) (36971,)


In [86]:
# Creating back_up X_train, y_train 
# Creating backup files 
X.to_csv('X_train_VA.csv',index=False)
y.to_csv('y_train_VA.csv',index=False)
y_County.to_csv('y_County_VA.csv',index=False)


In [87]:
# Using train_test_split() to randomly split the given training dataset into training and cross validation 
# data by 70:30 percent ratio respectively. 
X_train, X_cross_validation, y_train, y_cross_validation = train_test_split(X,y, test_size=0.3, random_state=42)
print(X_train.shape,X_cross_validation.shape)

(25879, 308) (11092, 308)


In [88]:
y_cross_validation.value_counts()

0    6525
1    4567
Name: Severity, dtype: int64

###  Creating model using random forest

In [89]:
pipe = Pipeline([
    ('rf', RandomForestClassifier())
])

In [90]:
clfRandom = RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [91]:
parameters = {
    'rf__n_estimators': [100,200,300],
    'rf__max_depth': [50,100,500],
    'rf__min_samples_split': [2,4],
}

In [102]:
parameters_2 = {
    'rf__n_estimators': [100,150,200],
    'rf__max_depth': [20,30,40,50],
    'rf__min_samples_split': [2,4,6],
}

In [103]:
clf_GS_Model_2 = GridSearchCV(pipe, parameters_2, scoring=make_scorer(f1_score))

In [92]:
clf_GS_Model_1 = GridSearchCV(pipe, parameters, scoring=make_scorer(f1_score))

In [93]:
# %time clf_GS_Model_1.fit(X_train, y_train)
%time clf_GS_Model_1.fit(X_train, y_train)

Wall time: 24min 20s


GridSearchCV(cv=None, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('rf',
                                        RandomForestClassifier(bootstrap=True,
                                                               ccp_alpha=0.0,
                                                               class_weight=None,
                                                               criterion='gini',
                                                               max_depth=None,
                                                               max_features='auto',
                                                               max_leaf_nodes=None,
                                                               max_samples=None,
                                                               min_impurity_decrease=0.0,
                                                               min_impurity_split=None,
                                            

In [104]:
%time clf_GS_Model_2.fit(X_train, y_train)

Wall time: 34min 25s


GridSearchCV(cv=None, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('rf',
                                        RandomForestClassifier(bootstrap=True,
                                                               ccp_alpha=0.0,
                                                               class_weight=None,
                                                               criterion='gini',
                                                               max_depth=None,
                                                               max_features='auto',
                                                               max_leaf_nodes=None,
                                                               max_samples=None,
                                                               min_impurity_decrease=0.0,
                                                               min_impurity_split=None,
                                            

In [94]:
pd.DataFrame(clf_GS_Model_1.cv_results_).sort_values("rank_test_score").head(5)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
4       14.834043      0.139576         0.331820        0.002100   
5       22.323524      0.211414         0.499326        0.012138   
17      22.267755      0.119601         0.499916        0.008282   
15       7.373949      0.025912         0.170310        0.001025   
11      22.207189      0.177436         0.495126        0.004916   

   param_rf__max_depth param_rf__min_samples_split param_rf__n_estimators  \
4                   50                           4                    200   
5                   50                           4                    300   
17                 500                           4                    300   
15                 500                           4                    100   
11                 100                           4                    300   

                                               params  split0_test_score  \
4   {'rf__max_depth': 50, 'rf__min_samples_split':...           0.710208   
5   {'rf__max_depth': 50, 'rf__min_samples_split':...           0.708467   
17  {'rf__max_depth': 500, 'rf__min_samples_split'...           0.708094   
15  {'rf__max_depth': 500, 'rf__min_samples_split'...           0.704744   
11  {'rf__max_depth': 100, 'rf__min_samples_split'...           0.706151   

    split1_test_score  split2_test_score  split3_test_score  \
4            0.702973           0.711693           0.715196   
5            0.706600           0.707826           0.714090   
17           0.705776           0.708954           0.710695   
15           0.711543           0.706045           0.711305   
11           0.706652           0.706449           0.713012   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
4            0.713496         0.710713        0.004218                1  
5            0.714976         0.710392        0.003445                2  
17           0.714909         0.709686        0.003055                3  
15           0.713364         0.709400        0.003372                4  
11           0.711880         0.708829        0.002979                5

In [105]:
# Viewing The Best Parameters
print('Best n estimator:', clf_GS_Model_2.best_estimator_.get_params()['rf__n_estimators'])
print('Best max_depth:', clf_GS_Model_2.best_estimator_.get_params()['rf__max_depth'])
print('Best min_samples_split:', clf_GS_Model_2.best_estimator_.get_params()['rf__min_samples_split'])

Best n estimator: 200
Best max_depth: 20
Best min_samples_split: 2


In [107]:
y_train_pred = clf_GS_Model_2.best_estimator_.predict(X_train)
# y_train_pred = clfRandom.predict(X_train)

f1_score(y_train, y_train_pred)

0.9515538447094168

In [97]:
y_train.unique()

array([1, 0], dtype=int64)

In [108]:
confusion_matrix(y_train, y_train_pred)

array([[14712,   408],
       [  624, 10135]], dtype=int64)

In [109]:
y_cross_validation_pred= clf_GS_Model_2.best_estimator_.predict(X_cross_validation)
# y_cross_validation_pred= clfRandom.predict(X_cross_validation)
f1_score(y_cross_validation, y_cross_validation_pred)

0.7179046801202235

In [101]:
confusion_matrix(y_cross_validation, y_cross_validation_pred)

array([[5078, 1447],
       [1237, 3330]], dtype=int64)

In [8]:
X =pd.read_csv('X_train.csv')
y =pd.read_csv('y_train.csv')

In [9]:
# Using train_test_split() to randomly split the given training dataset into training and cross validation 
# data by 70:30 percent ratio respectively. 
X_train, X_cross_validation, y_train, y_cross_validation = train_test_split(X,y, test_size=0.3, random_state=42)
print(X_train.shape,X_cross_validation.shape)

(636526, 312) (272797, 312)


In [10]:
del(X)
del(y)

In [11]:
from sklearn.preprocessing import MinMaxScaler

In [12]:
# Used MinMaxScaler() function to further normalize features on the scale of (0 to 1)
scaler = MinMaxScaler()
scaler.fit(X_train)
# Normalized traning data set
normalized_train = scaler.transform(X_train)

In [13]:
del(X_train)

In [14]:
normalized_train.shape

(636526, 312)

In [15]:
normalized_cv = scaler.transform(X_cross_validation)
normalized_cv.shape

(272797, 312)

In [16]:
del(X_cross_validation)

In [17]:
from sklearn.svm import SVC

In [ ]:
%%time
clf = SVC(gamma='auto')
clf.fit(normalized_train, y_train)

D:\Softwares\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import BaggingClassifier

In [20]:
n_estimators = 10

In [ ]:
%%time
clf = OneVsRestClassifier(BaggingClassifier(SVC(kernel='linear',probability=True,class_weight='balanced'), max_samples=1.0 / n_estimators, n_estimators=n_estimators))
clf.fit(normalized_train, y_train)